export default{
    Venda:{
        id : "",
        contrato : "",
        chip : "",
        rastreador : "",
        linha : "",
        cliente : "",
        cpfcnpj : "",
        RGIE: "",
        dataNascimento : "",
        endereco : "",
        bairro : "",
        cidadeUF : "",
        cep : "",
        telefoneResidencial : "",
        telefoneCelular : "",
        email : "",
        marca : "",
        modelo : "",
        cor : "",
        placa : "",
        panico1 : "",
        panico2 : "",
        valorRastreador : "",
        valorBotao : "",
        localvenda : "",
        vendendorIndicacao : "",
        localInstalacao : "",
        instalador : "",
        dataVenda : "",
        dataInstalacao : "",
        observacoes : "",
        parcelas : "",
        tipoPagamento : "",
        BotaoExtra : "",
        BotaoExtraQuantidade : "",
        tipoVeiculo : "",
        qtdParcelas :""
    }
}