// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Models;

namespace api.Migrations
{
    [DbContext(typeof(VendaContext))]
    partial class VendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("api.Models.Venda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BotaoExtra")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("BotaoExtraQuantidade")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PagamentoCredito")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PagamentoDebito")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PagamentoEspecie")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PagamentoFinanciamento")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PagamentoOutros")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RGIE")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("bairro")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("caminhao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("carro")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("cep")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("chip")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("cidadeUF")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("cliente")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("contrato")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("cor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("cpfcnpj")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dataInstalacao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dataNascimento")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("dataVenda")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("endereco")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("instalador")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("linha")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("localInstalacao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("localvenda")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("marca")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("modelo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("moto")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("observacoes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("outros")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("panico1")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("panico2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("parcelas")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("placa")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("qtdParcelas")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("rastreador")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("telefoneCelular")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("telefoneResidencial")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("valorBotao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("valorRastreador")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("vendendorIndicacao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("id");

                    b.ToTable("Vendas");
                });
#pragma warning restore 612, 618
        }
    }
}
